// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xivonturgevryfycspdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpdm9udHVyZ2V2cnlmeWNzcGRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODAwMzQsImV4cCI6MjA3NDY1NjAzNH0.FvjDxjWzKO95N2uA6Hn0LizPlHwTNd-IkOCHFODGFSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});